app:
  plugins:
    - name: '@tpb/plugin-hello-world'
    - name: '@tpb/plugin-gitlab-loblaw'
      version: '^0.0.18'
backend:
  plugins:
    - name: '@tpb/plugin-hello-world-backend'
    - name: '@tpb/plugin-gitlab-backend'